#!/usr/bin/env perl

use strict;
use warnings;
use Data::Dumper;
use File::Slurp qw(read_file);
use JSON::MaybeXS qw(decode_json);

my $location_filename = 'location_history/your_location_history.json';

my ($data_dir) = @ARGV;
validate_dir($data_dir);

count_locations();
count_posts();
count_marketplace();
count_saved_items();

sub count_saved_items {
	my $no_saved_items_filename = 'saved_items/no-data.txt';
	if (-f $no_saved_items_filename) {
		print "- 0 saved_items entries\n";
	} else {
		warn "unimplemented saved_items count";
	}
}

sub count_marketplace {
	my $no_marketplace_filename = 'marketplace/no-data.txt';
	if (-f $no_marketplace_filename) {
		print "- 0 marketplace entries\n";
	} else {
		warn "unimplemented marketplace count";
	}
}

sub count_posts {
	my $your_posts_filename = 'posts/your_posts.json';
	my $your_posts = read_json($your_posts_filename);
	my @status_updates = @{ $your_posts->{'status_updates'} };
	my $status_update_count = scalar @status_updates;
	print "- $status_update_count status updates\n";

	# TODO: status updaetes per year/month
}

sub count_locations {
	my $locs = read_json($location_filename);

	my @locs = @{$locs->{'location_history'}};

	my $loc_count = scalar @locs;
	print "- $loc_count location entries\n";
}

sub top_keys {
	my ($hash) = @_;

	my @keys = keys %$hash;

	print "% " . join("\n% ", @keys) . "\n";
}

sub read_json {
	my ($json_filename) = @_;
	my $file_contents = read_file($json_filename);

	my $json = JSON::MaybeXS->new->allow_nonref;
	my $js_ref = $json->decode($file_contents);
	die "no ref back from json->decode()" unless $js_ref;

	return $js_ref;
}

sub validate_dir {
	my ($data_dir) = @_;

	# is it a directory???
	unless (-d $data_dir) {
		die "not a directory: $data_dir";
	}

	chdir($data_dir) or die "couldn't chdir($data_dir): $!";

	# does it contain the right subdirectories???
	my @top_dirs = qw( about_you ads apps_and_websites calls_and_messages
			comments events following_and_followers friends
			groups likes_and_reactions location_history
			marketplace messages other_activity pages
			payment_history photos_and_videos posts
			profile_information saved_items search_history
			security_and_login_information your_places);
	foreach my $dir (@top_dirs) {
		unless (-d $dir) {
			die "no $dir directory in $data_dir";
		}
	}

	# how about a file?
	unless (-f $location_filename) {
		die "no  $location_filename";
	}

	print "$data_dir looks like a Facebook data dump\n";
}
